import sys
import os
import math
from datetime import datetime, UTC, date, timedelta
import requests
from flask import Flask, request, render_template, jsonify, Response
from dotenv import load_dotenv

from weatherprediction.exception import WeatherException
from weatherprediction.logger import logger
from weatherprediction.pipeline.predict_pipeline import CustomData, PredictPipeline

import json

load_dotenv()
app = Flask(__name__)

WEATHER_API_KEY = os.getenv("WEATHER_API_KEY", "")
OWM_BASE = "https://api.openweathermap.org/data/2.5"
OWM_GEO  = "https://api.openweathermap.org/geo/1.0"

# ── Historical climate normals — loaded ONCE at startup, cached in memory ──────
# Generated by:  python scripts/generate_historical_averages.py
# Format: HIST_AVG[city_name][str(day_of_year)] = {tmax, tmin, precip, wind, samples}
_HIST_AVG_PATH = os.path.join(os.path.dirname(__file__), "artifacts", "historical_daily_averages.json")
try:
    with open(_HIST_AVG_PATH, "r", encoding="utf-8") as _f:
        HIST_AVG: dict = json.load(_f)
    logger.info(f"Loaded historical averages: {len(HIST_AVG)} cities, "
                f"{sum(len(v) for v in HIST_AVG.values())} city-doy entries")
except FileNotFoundError:
    HIST_AVG = {}
    logger.warning(f"Historical averages file not found at {_HIST_AVG_PATH}. "
                   "Run scripts/generate_historical_averages.py to generate it.")


# ── Helpers ────────────────────────────────────────────────────────────────────
PREDICTION_FEEDBACK_LOG = os.path.join("logs", "prediction_feedback.csv")

def log_prediction_feedback(city: str, lat: float, lon: float, date_str: str, prediction: str, probability: float, confidence: float, features: dict):
    """
    Log live inference predictions to CSV feedback log with exact geographical
    coordinates for accurate historical outcome fetching.
    """
    try:
        os.makedirs(os.path.dirname(PREDICTION_FEEDBACK_LOG), exist_ok=True)
        with open(PREDICTION_FEEDBACK_LOG, mode="a", encoding="utf-8") as f:
            if f.tell() == 0:
                f.write("timestamp,city,lat,lon,predict_date,prediction,probability,confidence,temp_max,temp_min,precip_sum,weather_code\n")
            
            ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
            tmax = features.get("temperature_2m_max", "")
            tmin = features.get("temperature_2m_min", "")
            prec = features.get("precipitation_sum", "")
            wcode = features.get("weather_code", "")
            
            f.write(f"{ts},{city},{lat},{lon},{date_str},{prediction},{probability},{confidence},{tmax},{tmin},{prec},{wcode}\n")
            logger.info(f"Logged prediction feedback -> {city} ({lat},{lon}) [{date_str}]: {prediction} ({probability}%)")
    except Exception as exc:
        logger.warning(f"Could not write prediction log: {exc}")


def owm_get(endpoint, params: dict):
    """Call OpenWeatherMap API and return JSON or None on error."""
    params["appid"] = WEATHER_API_KEY
    try:
        r = requests.get(endpoint, params=params, timeout=8)
        r.raise_for_status()
        return r.json()
    except Exception as exc:
        logger.warning(f"OWM API error: {exc}")
        return None


def weather_icon_class(icon_code: str) -> str:
    """Map OWM icon codes to CSS icon class names."""
    mapping = {
        "01d": "sun", "01n": "moon",
        "02d": "partly-cloudy", "02n": "partly-cloudy-night",
        "03d": "cloudy", "03n": "cloudy",
        "04d": "overcast", "04n": "overcast",
        "09d": "rain", "09n": "rain",
        "10d": "rain-sun", "10n": "rain",
        "11d": "thunder", "11n": "thunder",
        "13d": "snow", "13n": "snow",
        "50d": "fog", "50n": "fog",
    }
    return mapping.get(icon_code, "sun")


def aqi_label(aqi: int) -> dict:
    labels = {
        1: {"text": "Good",        "color": "#22c55e"},
        2: {"text": "Fair",        "color": "#84cc16"},
        3: {"text": "Moderate",    "color": "#f59e0b"},
        4: {"text": "Poor",        "color": "#ef4444"},
        5: {"text": "Very Poor",   "color": "#7c3aed"},
    }
    return labels.get(aqi, {"text": "Unknown", "color": "#6b7280"})


def owm_id_to_wmo_code(owm_id: int) -> int:

    if owm_id == 800:
        return 0    # Clear sky
    if owm_id == 801:
        return 1    # Mainly clear
    if owm_id == 802:
        return 2    # Partly cloudy
    if owm_id in (803, 804):
        return 3    # Overcast
    if 700 <= owm_id <= 799:
        # Atmosphere: mist(701), smoke(711), haze(721), dust(731,761),
        # fog(741), sand(751), ash(762), squall(771), tornado(781)
        return 45   # Fog / haze
    if 300 <= owm_id <= 321:
        # Drizzle: light(300,301), moderate(302,311), heavy(312,314,321)
        if owm_id in (300, 301, 310):
            return 51   # Light drizzle
        if owm_id in (302, 311, 313):
            return 53   # Moderate drizzle
        return 55       # Dense drizzle
    if 500 <= owm_id <= 531:
        # Rain
        if owm_id == 500:
            return 61   # Slight rain
        if owm_id == 501:
            return 63   # Moderate rain
        if owm_id in (502, 503, 504):
            return 65   # Heavy rain (dataset max)
        if owm_id in (511, 520):
            return 61   # Freezing / light shower → slight rain
        if owm_id in (521, 522, 531):
            return 63   # Shower rain
        return 61
    if 600 <= owm_id <= 622:
        # Snow — rare for India; map to light rain equivalent
        return 61
    if 200 <= owm_id <= 232:
        # Thunderstorm — cap at 65 (dataset max; WMO 95+ not in training data)
        return 65
    return 3  # fallback: overcast


def compute_moon_phase(dt: datetime = None) -> dict:
    """
    Compute moon phase using a standard lunar cycle formula.
    Returns phase_name, phase_icon, and illumination (0-1).
    No external API needed.
    """
    if dt is None:
        dt = datetime.now(UTC)

    # Known new moon reference: Jan 6, 2000
    known_new_moon = datetime(2000, 1, 6, 18, 14, tzinfo=UTC)
    lunar_cycle = 29.53058867  # days

    delta = dt - known_new_moon
    days_since = delta.total_seconds() / 86400.0
    phase_position = (days_since % lunar_cycle) / lunar_cycle  # 0.0 – 1.0

    # Illumination fraction (simple cosine model)
    illumination = (1 - math.cos(2 * math.pi * phase_position)) / 2

    # Phase name buckets
    if phase_position < 0.0625:
        name, icon = "New Moon", "🌑"
    elif phase_position < 0.1875:
        name, icon = "Waxing Crescent", "🌒"
    elif phase_position < 0.3125:
        name, icon = "First Quarter", "🌓"
    elif phase_position < 0.4375:
        name, icon = "Waxing Gibbous", "🌔"
    elif phase_position < 0.5625:
        name, icon = "Full Moon", "🌕"
    elif phase_position < 0.6875:
        name, icon = "Waning Gibbous", "🌖"
    elif phase_position < 0.8125:
        name, icon = "Last Quarter", "🌗"
    elif phase_position < 0.9375:
        name, icon = "Waning Crescent", "🌘"
    else:
        name, icon = "New Moon", "🌑"

    return {
        "name": name,
        "icon": icon,
        "illumination": round(illumination * 100),
        "position": round(phase_position * 100),
    }


# ── Pages ──────────────────────────────────────────────────────────────────────
@app.route("/", methods=["GET"])
def index():
    """GOOD WEATHER landing page."""
    return render_template("index.html")


@app.route("/weather", methods=["GET"])
def weather_dashboard():
    """Full weather dashboard for a given city."""
    city = request.args.get("city", "London")
    lat  = request.args.get("lat", None)
    lon  = request.args.get("lon", None)

    # If lat/lon provided (geolocation), use them directly
    if lat and lon:
        loc_params = {"lat": lat, "lon": lon, "units": "metric"}
    else:
        loc_params = {"q": city, "units": "metric"}

    # ── Current weather ────────────────────────────────────────────────────────
    current = owm_get(f"{OWM_BASE}/weather", {**loc_params})
    if not current:
        return render_template("weather.html", error=f"City '{city}' not found.", city=city)

    # Extract coordinates for subsequent calls
    coord_lat = current["coord"]["lat"]
    coord_lon = current["coord"]["lon"]

    # ── 5-day / 3-hour forecast ────────────────────────────────────────────────
    forecast_data = owm_get(f"{OWM_BASE}/forecast", {"lat": coord_lat, "lon": coord_lon, "units": "metric"})

    # ── Air quality ────────────────────────────────────────────────────────────
    aqi_data = owm_get(f"{OWM_BASE}/air_pollution", {"lat": coord_lat, "lon": coord_lon})

    # ── Process current weather ────────────────────────────────────────────────
    icon_code   = current["weather"][0]["icon"]
    description = current["weather"][0]["description"].title()
    temp        = round(current["main"]["temp"])
    feels_like  = round(current["main"]["feels_like"])
    temp_min    = round(current["main"]["temp_min"])
    temp_max    = round(current["main"]["temp_max"])
    humidity    = current["main"]["humidity"]
    pressure    = current["main"]["pressure"]
    wind_speed  = round(current["wind"]["speed"] * 3.6, 1)   # m/s → km/h
    wind_deg    = current["wind"].get("deg", 0)
    visibility  = round(current.get("visibility", 10000) / 1000, 1)
    sunrise_ts  = current.get("sys", {}).get("sunrise", 0)
    sunset_ts   = current.get("sys", {}).get("sunset", 0)
    city_name   = current.get("name") or city
    country     = current.get("sys", {}).get("country", "")
    timezone    = current["timezone"]          # seconds offset from UTC

    # Last updated timestamp (local time of the city)
    from datetime import timezone as tz
    import datetime as dt_module
    utc_now = dt_module.datetime.now(dt_module.UTC)
    city_offset = dt_module.timedelta(seconds=timezone)
    city_now = utc_now + city_offset
    last_updated = city_now.strftime("%H:%M, %a %d %b")

    # Wind direction text
    dirs = ["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"]
    wind_dir = dirs[round(wind_deg / 22.5) % 16]

    # ── Process forecast into: daily summary + per-day hourly breakdown ────────
    # Use city's LOCAL date (not UTC) so "Today" card matches what the user sees
    today_str = city_now.strftime("%Y-%m-%d")

    # Build a dict: date_str → list of 3-hour slots (hourly_items)
    day_slots_map = {}   # date → [slot, ...]
    if forecast_data:
        for item in forecast_data["list"]:
            date_str = item["dt_txt"].split(" ")[0]
            if date_str not in day_slots_map:
                day_slots_map[date_str] = []
            day_slots_map[date_str].append(item)

    # Build daily summary list (max 5 days)
    daily_list = []
    for date_str, slots in list(day_slots_map.items())[:5]:
        highs = [s["main"]["temp_max"] for s in slots]
        lows  = [s["main"]["temp_min"] for s in slots]
        icons = [s["weather"][0]["icon"] for s in slots]
        precips = [s.get("pop", 0) for s in slots]
        icon_c = max(set(icons), key=icons.count)

        # Per-day hourly breakdown for expandable rows
        day_hourly = []
        for s in slots:
            ic = s["weather"][0]["icon"]
            day_hourly.append({
                "time":       s["dt_txt"].split(" ")[1][:5],
                "temp":       round(s["main"]["temp"]),
                "icon_code":  ic,
                "icon_class": weather_icon_class(ic),
                "precip":     round(s.get("pop", 0) * 100),
                "desc":       s["weather"][0]["description"].title(),
            })

        daily_list.append({
            "date":       date_str,
            "is_today":   date_str == today_str,
            "high":       round(max(highs)),
            "low":        round(min(lows)),
            "icon_code":  icon_c,
            "icon_class": weather_icon_class(icon_c),
            "desc":       slots[0]["weather"][0]["description"].title(),
            "precip":     round(max(precips) * 100),
            "hourly":     day_hourly,
        })

    # Today hi/lo from forecast (more accurate than current weather min/max)
    today_forecast = day_slots_map.get(today_str)
    if today_forecast:
        today_high = round(max(s["main"]["temp_max"] for s in today_forecast))
        today_low  = round(min(s["main"]["temp_min"] for s in today_forecast))
    else:
        today_high = temp_max
        today_low  = temp_min

    # ── Process hourly (next 48h = 16 slots of 3-hour intervals) ─────────────
    hourly_list = []
    if forecast_data:
        for item in forecast_data["list"][:16]:
            ic = item["weather"][0]["icon"]
            hourly_list.append({
                "dt_txt":     item["dt_txt"],
                "time":       item["dt_txt"].split(" ")[1][:5],
                "temp":       round(item["main"]["temp"]),
                "icon_code":  ic,
                "icon_class": weather_icon_class(ic),
                "precip":     round(item.get("pop", 0) * 100),
                "desc":       item["weather"][0]["description"].title(),
                "wind_speed": round(item["wind"]["speed"] * 3.6, 1),
                "wind_deg":   item["wind"].get("deg", 0),
                "humidity":   item["main"]["humidity"],
                "clouds":     item.get("clouds", {}).get("all", 0),
            })

    # ── AQI ────────────────────────────────────────────────────────────────────
    aqi_index = 1
    aqi_info  = aqi_label(1)
    aqi_components = {}
    if aqi_data and aqi_data.get("list"):
        aqi_index      = aqi_data["list"][0]["main"]["aqi"]
        aqi_info       = aqi_label(aqi_index)
        aqi_components = aqi_data["list"][0]["components"]

    # ── Moon phase (pure math, no API) ────────────────────────────────────────
    moon = compute_moon_phase(utc_now)

    ctx = {
        "city":           city_name,
        "country":        country,
        "lat":            coord_lat,
        "lon":            coord_lon,
        "temp":           temp,
        "feels_like":     feels_like,
        "temp_min":       temp_min,
        "temp_max":       temp_max,
        "today_high":     today_high,
        "today_low":      today_low,
        "humidity":       humidity,
        "pressure":       pressure,
        "wind_speed":     wind_speed,
        "wind_deg":       wind_deg,
        "wind_dir":       wind_dir,
        "visibility":     visibility,
        "description":    description,
        "icon_code":      icon_code,
        "icon_class":     weather_icon_class(icon_code),
        "sunrise_ts":     sunrise_ts,
        "sunset_ts":      sunset_ts,
        "timezone":       timezone,
        "last_updated":   last_updated,
        "daily":          daily_list,
        "hourly":         hourly_list,
        "aqi_index":      aqi_index,
        "aqi_text":       aqi_info["text"],
        "aqi_color":      aqi_info["color"],
        "aqi_components": aqi_components,
        "moon":           moon,
    }
    return render_template("weather.html", **ctx)




# ── API endpoints (JSON & Proxy) ─────────────────────────────────────────────
@app.route("/api/search", methods=["GET"])
def api_search():
    """City autocomplete search."""
    q = request.args.get("q", "")
    if len(q) < 2:
        return jsonify([])
    data = owm_get(f"{OWM_GEO}/direct", {"q": q, "limit": 5})
    if not data:
        return jsonify([])
    results = [
        {"name": item["name"], "country": item["country"],
         "state": item.get("state", ""),
         "lat": item["lat"], "lon": item["lon"]}
        for item in data
    ]
    return jsonify(results)


@app.route("/api/weather", methods=["GET"])
def api_weather():
    """Current weather JSON proxy."""
    lat = request.args.get("lat")
    lon = request.args.get("lon")
    city = request.args.get("city", "London")
    if lat and lon:
        params = {"lat": lat, "lon": lon, "units": "metric"}
    else:
        params = {"q": city, "units": "metric"}
    data = owm_get(f"{OWM_BASE}/weather", params)
    return jsonify(data or {"error": "not found"})


@app.route("/api/map/precipitation/<int:z>/<int:x>/<int:y>.png", methods=["GET"])
def api_map_precipitation(z, x, y):
    """Proxy OpenWeatherMap precipitation tiles server-side to protect API key."""
    url = f"https://tile.openweathermap.org/map/precipitation_new/{z}/{x}/{y}.png"
    try:
        r = requests.get(url, params={"appid": WEATHER_API_KEY}, timeout=5)
        if r.status_code == 200:
            return Response(r.content, mimetype="image/png", headers={"Cache-Control": "public, max-age=3600"})
        return ("Tile not found", r.status_code)
    except Exception as e:
        logger.warning(f"Map tile error: {e}")
        return ("Tile server error", 500)




# ── ML Feature Derivation ──────────────────────────────────────────────────────
def derive_features_from_owm(
    city: str,
    lat: float = None,
    lon: float = None,
    target_date_str: str = None,
):
    """
    Fetch OWM current & forecast data and derive all 15 model features
    matching the india_2000_2024_daily_weather.csv schema.

    Features derived
    ----------------
    temperature_2m_max          max daily temp (°C)
    temperature_2m_min          min daily temp (°C)
    apparent_temperature_max    max feels-like temp (°C)
    apparent_temperature_min    min feels-like temp (°C)
    precipitation_sum           total precipitation (mm)
    weather_code                WMO code approximated from OWM condition ID
    wind_speed_10m_max          max 10m wind speed (km/h)
    wind_gusts_10m_max          max 10m wind gust (km/h)
    wind_direction_10m_dominant dominant wind direction (°)
    rain_today                  1 if precipitation_sum > 0
    Day / Month / Year          from target_date_str
    city                        resolved OWM city name (for OHE)
    """
    from collections import Counter

    if not target_date_str:
        target_date_str = datetime.now().strftime("%Y-%m-%d")

    target_dt = datetime.strptime(target_date_str, "%Y-%m-%d").date()

    if lat and lon:
        loc_params = {"lat": lat, "lon": lon, "units": "metric"}
    else:
        loc_params = {"q": city, "units": "metric"}

    current = owm_get(f"{OWM_BASE}/weather", {**loc_params})
    if not current:
        raise ValueError(f"Could not retrieve weather data for '{city}'.")

    coord_lat     = current["coord"]["lat"]
    coord_lon     = current["coord"]["lon"]
    resolved_city = current.get("name", city)

    forecast_data = owm_get(
        f"{OWM_BASE}/forecast",
        {"lat": coord_lat, "lon": coord_lon, "units": "metric"},
    )

    # ── Filter forecast slots for the target date ──────────────────────────────
    day_slots = []
    if forecast_data and "list" in forecast_data:
        for slot in forecast_data["list"]:
            if slot["dt_txt"].split(" ")[0] == target_date_str:
                day_slots.append(slot)

    # Fallback: use current-weather data if no forecast slots for that date
    if not day_slots:
        day_slots = [{
            "main":   current["main"],
            "wind":   current.get("wind", {}),
            "clouds": current.get("clouds", {}),
            "rain":   current.get("rain", {}),
            "weather": current.get("weather", [{}]),
            "dt_txt": f"{target_date_str} 12:00:00",
        }]

    # ── Temperature (°C) ──────────────────────────────────────────────────────
    temperature_2m_max = round(max(s["main"]["temp_max"] for s in day_slots), 1)
    temperature_2m_min = round(min(s["main"]["temp_min"] for s in day_slots), 1)

    # ── Apparent (feels-like) temperature ─────────────────────────────────────
    feels_like_vals = [s["main"].get("feels_like", s["main"]["temp"]) for s in day_slots]
    apparent_temperature_max = round(max(feels_like_vals), 1)
    apparent_temperature_min = round(min(feels_like_vals), 1)

    # ── Precipitation (mm) ────────────────────────────────────────────────────
    precipitation_sum = round(
        sum(s.get("rain", {}).get("3h", 0.0) for s in day_slots), 1
    )
    # For India, snow is negligible — rain_sum ≈ precipitation_sum
    rain_sum  = precipitation_sum
    rain_today = 1 if precipitation_sum > 0.0 else 0

    # ── Wind (m/s → km/h) ─────────────────────────────────────────────────────
    wind_speed_10m_max = round(
        max(s["wind"].get("speed", 0.0) for s in day_slots) * 3.6, 1
    )
    max_gust_ms = max(
        s["wind"].get("gust", s["wind"].get("speed", 0.0) * 1.3)
        for s in day_slots
    )
    wind_gusts_10m_max = round(max_gust_ms * 3.6, 1)

    # ── Wind direction (dominant, degrees) ────────────────────────────────────
    wind_degs = [s["wind"].get("deg", 0) for s in day_slots]
    wind_direction_10m_dominant = float(
        Counter(wind_degs).most_common(1)[0][0] if wind_degs else 0
    )

    # ── WMO weather code ──────────────────────────────────────────────────────
    # Use the most severe (highest OWM ID category) condition across the day.
    owm_ids = []
    for s in day_slots:
        weather_list = s.get("weather", [])
        if weather_list:
            owm_ids.append(weather_list[0].get("id", 800))
    # Pick the ID that maps to the highest WMO code (most severe)
    if owm_ids:
        weather_code = max(owm_id_to_wmo_code(wid) for wid in owm_ids)
    else:
        weather_code = owm_id_to_wmo_code(current["weather"][0]["id"])

    logger.info(
        f"OWM IDs for {target_date_str}: {owm_ids}  →  WMO weather_code={weather_code}"
    )

    return {
        # ── Model features ──────────────────────────────────────────────────
        "temperature_2m_max":          temperature_2m_max,
        "temperature_2m_min":          temperature_2m_min,
        "apparent_temperature_max":    apparent_temperature_max,
        "apparent_temperature_min":    apparent_temperature_min,
        "humidity_3pm":                current["main"]["humidity"],
        "precipitation_sum":           precipitation_sum,
        "weather_code":                weather_code,
        "wind_speed_10m_max":          wind_speed_10m_max,
        "wind_gusts_10m_max":          wind_gusts_10m_max,
        "wind_direction_10m_dominant": wind_direction_10m_dominant,
        "rain_today":                  rain_today,
        "day":                         target_dt.day,
        "month":                       target_dt.month,
        "year":                        target_dt.year,
        "city":                        resolved_city,
        # ── Display & Metadata ───────────────────────────────────────────────
        "resolved_city": resolved_city,
        "lat":           coord_lat,
        "lon":           coord_lon,
        "country":       current.get("sys", {}).get("country", ""),
        "date_str":      target_date_str,
    }


# ── ML Predict ────────────────────────────────────────────────────────────────
@app.route("/predict-form", methods=["GET"])
def predict_form():
    """Serve the redesigned city & date picker ML prediction form."""
    return render_template("predict_form.html")


@app.route("/predict", methods=["POST"])
def predict():
    try:
        form = request.form
        city = form.get("city", "Delhi").strip() or "Delhi"
        lat = float(form["lat"]) if form.get("lat") and form["lat"].replace(".","").replace("-","").isdigit() else None
        lon = float(form["lon"]) if form.get("lon") and form["lon"].replace(".","").replace("-","").isdigit() else None
        target_date = form.get("date", datetime.now().strftime("%Y-%m-%d"))

        feat = derive_features_from_owm(city, lat, lon, target_date)

        data = CustomData(
            temperature_2m_max          = feat["temperature_2m_max"],
            temperature_2m_min          = feat["temperature_2m_min"],
            apparent_temperature_max    = feat["apparent_temperature_max"],
            apparent_temperature_min    = feat["apparent_temperature_min"],
            precipitation_sum           = feat["precipitation_sum"],
            weather_code                = feat["weather_code"],
            wind_speed_10m_max          = feat["wind_speed_10m_max"],
            wind_gusts_10m_max          = feat["wind_gusts_10m_max"],
            wind_direction_10m_dominant = feat["wind_direction_10m_dominant"],
            rain_today                  = feat["rain_today"],
            day                         = feat["day"],
            month                       = feat["month"],
            year                        = feat["year"],
            city                        = feat["city"],
        )

        df = data.get_data_as_dataframe()
        logger.info(f"Auto-derived Input DataFrame:\n{df.to_string()}")

        pipeline = PredictPipeline()
        adv = pipeline.predict_advanced(df)
        result = adv[0]

        # Log prediction to feedback tracker for production monitoring
        log_prediction_feedback(
            city        = feat["resolved_city"],
            lat         = feat["lat"],
            lon         = feat["lon"],
            date_str    = feat["date_str"],
            prediction  = result["prediction"],
            probability = result["probability"],
            confidence  = result["confidence"],
            features    = feat,
        )

        return render_template(
            "result.html",
            prediction   = result["prediction"],
            probability  = result["probability"],
            confidence   = result["confidence"],
            risk_level   = result["risk_level"],
            risk_color   = result["risk_color"],
            risk_bg      = result["risk_bg"],
            risk_border  = result["risk_border"],
            features     = feat,
            city         = feat["resolved_city"],
            country      = feat["country"],
            date         = feat["date_str"],
        )

    except Exception as e:
        logger.error(f"Prediction error: {e}")
        raise WeatherException(e, sys)


@app.route("/predict-multi", methods=["POST"])
def predict_multi():
    """5-day AI rain prediction timeline."""
    try:
        form = request.form
        city = form.get("city", "London").strip()
        lat = float(form["lat"]) if form.get("lat") else None
        lon = float(form["lon"]) if form.get("lon") else None

        pipeline = PredictPipeline()
        days_results = []

        for offset in range(5):
            target_dt = datetime.now() + timedelta(days=offset)
            target_date = target_dt.strftime("%Y-%m-%d")
            try:
                feat = derive_features_from_owm(city, lat, lon, target_date)
                data = CustomData(
                    temperature_2m_max          = feat["temperature_2m_max"],
                    temperature_2m_min          = feat["temperature_2m_min"],
                    apparent_temperature_max    = feat["apparent_temperature_max"],
                    apparent_temperature_min    = feat["apparent_temperature_min"],
                    precipitation_sum           = feat["precipitation_sum"],
                    weather_code                = feat["weather_code"],
                    wind_speed_10m_max          = feat["wind_speed_10m_max"],
                    wind_gusts_10m_max          = feat["wind_gusts_10m_max"],
                    wind_direction_10m_dominant = feat["wind_direction_10m_dominant"],
                    rain_today                  = feat["rain_today"],
                    day                         = feat["day"],
                    month                       = feat["month"],
                    year                        = feat["year"],
                    city                        = feat["city"],
                )
                df = data.get_data_as_dataframe()
                adv = pipeline.predict_advanced(df)
                result = adv[0]
                result["features"]    = feat
                result["date"]        = target_date
                result["day_label"]   = "Today" if offset == 0 else target_dt.strftime("%A")
                result["date_short"]  = target_dt.strftime("%d %b")
                days_results.append(result)
            except Exception as ex:
                logger.warning(f"Could not predict for {target_date}: {ex}")
                days_results.append({
                    "prediction": "N/A", "probability": 0, "confidence": 0,
                    "risk_level": "Unknown", "risk_color": "#6b7280",
                    "risk_bg": "rgba(107,114,128,0.12)", "risk_border": "rgba(107,114,128,0.35)",
                    "date": target_date, "day_label": target_dt.strftime("%A"),
                    "date_short": target_dt.strftime("%d %b"), "features": {},
                })

        return render_template(
            "predict_multi.html",
            city    = city,
            country = days_results[0].get("features", {}).get("country", "") if days_results else "",
            days    = days_results,
        )

    except Exception as e:
        logger.error(f"Multi-day prediction error: {e}")
        raise WeatherException(e, sys)


# ── /trends — Historical climate normals API ───────────────────────────────────
@app.route("/trends", methods=["GET"])
@app.route("/api/trends", methods=["GET"])
def api_trends():
    """
    Return historical daily averages for a city over a day-of-year window.

    Query params:
      city      : str  — must match a city name in HIST_AVG (case-sensitive)
      doy_start : int  — start day-of-year (1-365), default = today
      doy_end   : int  — end day-of-year   (1-365), default = doy_start + 29
      metric    : str  — one of: tmax, tmin, precip, wind (default: tmax)

    Returns JSON:
      {
        "city": "Delhi",
        "metric": "tmax",
        "doy_start": 220,
        "doy_end": 249,
        "data": [
          {"doy": 220, "value": 33.5, "samples": 25},
          ...
        ]
      }
    """
    city   = request.args.get("city", "")
    metric = request.args.get("metric", "tmax")

    # Default window: today ± 0 → +29 days (30-day window)
    today_doy = datetime.now(UTC).timetuple().tm_yday
    try:
        doy_start = int(request.args.get("doy_start", today_doy))
        doy_end   = int(request.args.get("doy_end",   today_doy + 29))
    except ValueError:
        return jsonify({"error": "doy_start and doy_end must be integers"}), 400

    if metric not in ("tmax", "tmin", "precip", "wind"):
        return jsonify({"error": f"Invalid metric '{metric}'. Choose: tmax, tmin, precip, wind"}), 400

    if not city:
        return jsonify({"error": "city param required"}), 400

    city_data = HIST_AVG.get(city)
    if city_data is None:
        # Try case-insensitive fallback
        city_lower = city.lower()
        for k in HIST_AVG:
            if k.lower() == city_lower:
                city_data = HIST_AVG[k]
                city = k
                break
        if city_data is None:
            available = sorted(HIST_AVG.keys())
            return jsonify({
                "error": f"City '{city}' not in historical dataset.",
                "available_cities": available
            }), 404

    # Collect doy range, wrapping around year end (e.g. 350 → 365 → 1 → 15)
    data = []
    total_days = doy_end - doy_start + 1
    for offset in range(max(total_days, 1)):
        doy = ((doy_start - 1 + offset) % 365) + 1   # 1-365, wraps
        entry = city_data.get(str(doy))
        if entry:
            data.append({
                "doy":     doy,
                "value":   entry[metric],
                "samples": entry["samples"],
            })

    return jsonify({
        "city":      city,
        "metric":    metric,
        "doy_start": doy_start,
        "doy_end":   doy_end,
        "data":      data,
    })


if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    debug_mode = os.getenv("FLASK_DEBUG", "false").lower() == "true"
    print("\n" + "="*50)
    print("  Weather Prediction App is starting...")
    print(f"  >> Local:   http://127.0.0.1:{port}")
    print(f"  >> Network: http://0.0.0.0:{port}")
    print(f"  >> Debug:   {debug_mode}")
    print("="*50 + "\n")
    app.run(host="0.0.0.0", port=port, debug=debug_mode)

